### ISSUE TITLE
Add an example for typescript usage

### ISSUE THREAD

**Issue by Rxann** [sindresorhus/ora#198]
I think that it would be great if someone could create a PR for adding ts examples to the readme!

**Comment by sindresorhus** [comment]
This is not the place to document how to use ESM with TypeScript.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by jason-henriksen** [comment]
You know what man, you have a popular project.   And it is absolutely not your fault that the current state of typescript makes your module difficult to use and import.

So if you would rather close a handful of defects every week, rather than add three lines to the bottom of your readme...  I guess that level of unhelpfulness is on you.

Great Project.  I'm happy to be using it.   But the tiniest bit of effort to add to a readme would make your work a lot more accessible to a lot more people.  I even put the markdown in another post.    I'm not clear why you would possibly be against adding pre-written documentation to your read me.  But whatever.  That's just your loss.

**Comment by aaaee2** [comment]
The author is just a goner asshole
